#!/usr/bin/env ruby
require "funny_yubikey_generator"
require "optparse"

colorize = false
dictionary = nil
number = 1

OptionParser.new do |opts|
  opts.banner = "Usage: generate_funny_yubikey [options]"
  opts.separator "Generate a yubikey TOP containing english words"
  opts.separator "Example: generate_funny_yubikey -c"

  opts.separator ""
  opts.separator "Options:"

  opts.on("-h", "--help", "Prints this help") do
    puts opts
    exit
  end
  opts.on("-c", "--color", "Output with colors") do
    colorize = true
  end
  opts.on("-n [NUMBER]", "--number", Integer, "Generate NUMBER Yubikey TOP") do |n|
    number = n if n
  end
  opts.on("-d [DICTIONARY]", "--dictionary", "Path to the file containing the list of words to pick from") do |dico|
    dictionary = dico
  end
end.parse!

generator = if dictionary
  path = File.expand_path(dictionary)
  unless File.exist?(path)
    warn("Could not find file: #{dictionary}")
    exit 1
  end
  FunnyYubikeyGenerator.from_dictionary(File.read(path))
else
  FunnyYubikeyGenerator.instance
end
number.times do
  puts generator.generate(colorize: colorize)
end
