#!/usr/bin/env ruby
require "funny_yubikey_generator"
require "optparse"

colorize = false
dictionary = nil

OptionParser.new do |opts|
  opts.banner = "Usage: generate_funny_yubikey [options]"
  opts.separator "Generate a yubikey TOP containing words"
  opts.separator "Example: generate_funny_yubikey -c"

  opts.separator ""
  opts.separator "Options:"

  opts.on("-h", "--help", "Prints this help") do
    puts opts
    exit
  end
  opts.on("-c", "--color", "Output with colors") do
    colorize = true
  end
  opts.on("-d", "--dictionary[=DICTIONARY]", "path to the file containing the list of words that will be used") do |dico|
    dictionary = dico
  end
end.parse!

generator = if dictionary
  raise "Could not find file #{dictionary}" unless File.exist?(dictionary)
  FunnyYubikeyGenerator.from_dictionary(File.read(dictionary))
else
  FunnyYubikeyGenerator.instance
end

puts generator.generate(colorize: colorize)
